{
 "title": "CraftbeerPi4",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CraftbeerPi4",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperatur Maische-Sud",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT mean(\"Temperatur\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '1') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "InduktionTemp___FhRwTsPKBqVuLzv5tpcCK9"
      }
     ]
    },
    {
     "alias": "Zieltemperatur Maische-Sud",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "KettleIndTarget___CkYppeUUMxBghfUXvNMr8q"
      }
     ]
    },
    {
     "alias": "Powerlevel Maische-Sud",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT mean(\"Powerlevel\") FROM \"mqttdevice_status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "KettleIndPower___ZWh5cCa8Jx4BBhjvsDiVpZ"
      }
     ]
    }
   ]
  },
  {
   "title": "Aktuelle Temperaturen",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Maische-Sud",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT mean(\"Temperatur\") FROM \"measurement\" WHERE (\"ID\" = '1') AND $timeFilter GROUP BY time(10s) fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "InduktionTemp___FhRwTsPKBqVuLzv5tpcCK9"
      }
     ]
    },
    {
     "alias": "Nachguss",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT last(\"Temperatur\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "NachgussTemp___XNXDq2ohLTZ3CPULizxjaC"
      }
     ]
    }
   ]
  },
  {
   "title": "Zieltemperaturen",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Maische-Sud",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT last(\"TargetTemp\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "KettleIndTarget___CkYppeUUMxBghfUXvNMr8q"
      }
     ]
    },
    {
     "alias": "Nachguss",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT last(\"TargetTemp\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "KettleNachgussTarget___ZaFm4dp2dcpY9gYkfe6RKv"
      }
     ]
    }
   ]
  },
  {
   "title": "Powerlevel",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Maische-Sud",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT last(\"Powerlevel\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '1') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "KettleIndPower___ZWh5cCa8Jx4BBhjvsDiVpZ"
      }
     ]
    },
    {
     "alias": "Nachguss",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "measurement",
     "query": "SELECT last(\"Powerlevel\") FROM \"mqttdevice_status\" WHERE (\"ID\" = '2') ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "source",
       "operator": "=",
       "value": "KettleNachgussPower___HQPqHcZAHDANnXmrfDUV99"
      }
     ]
    }
   ]
  }
 ]
}